# Inference config for Llama 3B Instruct.

model:
  model_name: "meta-llama/Llama-3.2-3B-Instruct"
  adapter_model: null  # Update for LoRA-tuned models.
  model_max_length: 512
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  load_pretrained_weights: True
  trust_remote_code: True

generation:
  max_new_tokens: 512
  batch_size: 4
