# Class: oumi.core.configs.InferenceConfig
# https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/inference_config.py

# Inference config for SmolLM 135M Instruct.

model:
  model_name: "HuggingFaceTB/SmolLM2-135M-Instruct"
  adapter_model: null # Update for LoRA-tuned models.
  model_max_length: 2048
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  load_pretrained_weights: True
  trust_remote_code: True

generation:
  max_new_tokens: 100
  batch_size: 4

engine: NATIVE
