# Class: oumi.core.configs.TrainingConfig
# https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/training_config.py

## Recipe and HPs used for Zephyr.7B:
## https://huggingface.co/alignment-handbook/zephyr-7b-sft-full

## Setup for training with 8, 80GB A100, GPUS.
## Adjust per_device_train_batch_size & gradient_accumulation_steps for your setup.

model:
  model_name: "mistralai/Mistral-7B-v0.1"
  trust_remote_code: True
  model_max_length: 2048
  chat_template: "zephyr"
  attn_implementation: "sdpa"

data:
  train:
    datasets:
      - dataset_name: "HuggingFaceH4/ultrachat_200k"
        split: "train_sft"
        shuffle: True
        seed: 42
    target_col: "text"

training:
  optimizer: "adamw_torch"
  use_peft: False
  trainer_type: "TRL_SFT"
  enable_gradient_checkpointing: True
  per_device_train_batch_size: 16
  gradient_accumulation_steps: 1 # Effective batch-size is 128=16x(1)x8
  learning_rate: 2.0e-05
  lr_scheduler_type: "cosine"
  output_dir: "output/zephyr-7b-sft-full"
  logging_dir: ${training.output_dir}/runs
  logging_first_step: True
  logging_steps: 25
  warmup_ratio: 0.1
  gradient_checkpointing_kwargs:
    use_reentrant: False # So gradients flow from frozen (non FT) input embeddings
  max_steps: -1
  num_train_epochs: 1
  save_steps: 100
  mixed_precision_dtype: "BF16"
  # resume_from_checkpoint: "your-checkpoint-directory" # Optional
  trainer_kwargs:
    dataset_text_field: ${data.train.target_col}
    max_seq_length: ${model.model_max_length}
    packing: True # Enabled for faster training
