name: zephyr-7b-qlora-sft

num_nodes: 1  # Set it to N for multi-node training.

resources:
  accelerators: {"A100": 8}

  disk_size: 200  # Disk size in GB
  # region: us-west3  # Uncomment this line to only consider a specific region.

  any_of:
    - use_spot: true
    - use_spot: false

# Upload working directory to remote ~/sky_workdir.
workdir: .

# Mount local files.
file_mounts:
  ~/.netrc: ~/.netrc # WandB credentials
  # Mount GCP bucket to save the checkpoints.
  # See https://github.com/oumi-ai/oumi/wiki/Clouds-Setup#mounting-gcs-buckets
  # for documentation on using GCS buckets.
  /output_dir_gcs:
    source: gs://oumi-dev-us-central1
    store: gcs
    mode: MOUNT

envs:
  WANDB_PROJECT: oumi-train
  HF_TOKEN: null # forces the user to pass it
  OUMI_RUN_NAME: "zephyr.7b.qlora"

setup: |
  set -e
  pip install uv && uv pip install '.[gpu]'

run: |
  set -e  # Exit if any command failed.
  source ./configs/examples/misc/sky_init.sh

  set -x
  oumi distributed torchrun \
      -m oumi train \
      -c configs/projects/zephyr/sft/qlora_train.yaml \
      --training.run_name "${OUMI_RUN_NAME}.${SKYPILOT_TASK_ID}" \
      --training.enable_wandb true \
      --training.enable_tensorboard true \
      --training.include_performance_metrics false \
      --training.output_dir "/output_dir_gcs/panos/output/${OUMI_RUN_NAME}"

  echo "Node ${SKYPILOT_NODE_RANK} is all done!"
