# Eval config for Llama 1B Instruct.

model:
  model_name: "meta-llama/Llama-3.2-1B-Instruct"
  adapter_model: null  # Update for LoRA-tuned models.
  model_max_length: 131072
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  load_pretrained_weights: True
  trust_remote_code: True

generation:
  batch_size: 4
lm_harness_params:
  tasks:
    - "m_mmlu_en"
  num_fewshot: 5
