name: phi3-dpo

num_nodes: 1  # Set it to N for multi-node training.

resources:
  # Use 1 of the following GPUs depending on availability. No preference.
  # To view other GPU types use the following commands:
  # `sky show-gpus`, `sky show-gpus -a`
  accelerators: {"A40", "A10", "A10g", "A100-80GB-SXM"}
  # To configure single-node, multi-gpu (N GPUs) training, set `accelerators:` above to
  # something like this: {"A40": N}

  disk_size: 200  # Disk size in GB
  # disk_tier: medium # medium is the default.
  # region: us-west3  # Uncomment this line to only consider a specific region.

  any_of:
    - use_spot: true  # See https://github.com/oumi-ai/oumi/wiki/Clouds-Setup#spot-vms-on-gcp
    - use_spot: false

# Upload working directory to remote ~/sky_workdir.
workdir: .

# Mount local files.
file_mounts:
  ~/.netrc: ~/.netrc # WandB credentials

envs:
  WANDB_PROJECT: oumi-train
  OUMI_RUN_NAME: phi3.dpo.nvidia.24g

setup: |
  set -e
  pip install uv && uv pip install '.[gpu]'

run: |
  set -e  # Exit if any command failed.
  source ./configs/examples/misc/sky_init.sh

  set -x
  torchrun \
      --nnodes=${OUMI_NUM_NODES} \
      --node-rank=${SKYPILOT_NODE_RANK} \
      --nproc-per-node=${SKYPILOT_NUM_GPUS_PER_NODE} \
      --master-addr=${OUMI_MASTER_ADDR} \
      --master-port=8007 \
      -m oumi.train \
      -c configs/recipes/phi3/dpo/nvidia_24g_train.yaml \
      "training.run_name='${OUMI_RUN_NAME}.${SKYPILOT_TASK_ID}'" \
      "training.output_dir=train/" \
      "training.enable_wandb=true" \
      "training.enable_tensorboard=true" \
      "training.include_performance_metrics=false" \
      "training.per_device_train_batch_size=4" \
      "training.max_steps=20" \
      "training.logging_steps=10"

  echo "Node ${SKYPILOT_NODE_RANK} is all done!"
