################################################
# Training Parameters : Q-LoRA SFT of Llama3.1 #
################################################

# We replicate the training parameters of:
# (1) https://github.com/pytorch/torchtune/blob/main/recipes/configs/llama3_1/8B_qlora_single_device.yaml

# Except:
# 1. We finetune the *base* Llama 3.1 model - not the already instruction-tuned one.
# 2. We apply a max sequence length of 8192 and we use an 8-bit Adam optimizer.
# 3. Because we intend to train with 4 A100-GPUs (instead of 1) to maintain the
# effective batch size of 32 - we reduce the grad_accumulation to 4 (instead of 16).

model:
  model_name: "meta-llama/Meta-Llama-3.1-8B"
  chat_template: "chat_ml"
  model_max_length: 8192
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  trust_remote_code: True

data:
  train:
    datasets:
      - dataset_name: "yahma/alpaca-cleaned"
        shuffle: True
    target_col: "prompt"
    seed: 123

training:
  trainer_type: TRL_SFT
  num_train_epochs: 1
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  learning_rate: 3.0e-4
  warmup_steps: 100
  lr_scheduler_type: "cosine"
  optimizer: "adamw_8bit"
  weight_decay: 0.01
  enable_gradient_checkpointing: True
  gradient_checkpointing_kwargs:
    use_reentrant: False
  seed: 123
  ddp_find_unused_parameters: False
  use_peft: True
  save_steps: 0
  save_epoch: True
  logging_steps: 50
  logging_first_step: True
  log_model_summary: True
  include_performance_metrics: True
  enable_wandb: True

peft:
  q_lora: True
  q_lora_bits: 4
  bnb_4bit_compute_dtype: "bfloat16"
  bnb_4bit_quant_type: "nf4"
  lora_r: 8
  lora_alpha: 16
  lora_target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj" #
    - "down_proj" # Since (1) applies it to MLP.
    - "up_proj"   #
