# Eval config for Aya.
#
# Usage:
#   oumi evaluate -c configs/projects/aya/evaluation/eval.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/evaluate/evaluate.html
#   - Config class: oumi.core.configs.EvaluationConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/evaluation_config.py
#   - Other eval configs: configs/**/evaluation/

model:
  model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct"
  model_max_length: 4096
  torch_dtype_str: "bfloat16"
  trust_remote_code: True
  attn_implementation: "sdpa"

tasks:
  - evaluation_platform: lm_harness
    task_name: m_mmlu_ar
    eval_kwargs:
      num_fewshot: 5
  - evaluation_platform: lm_harness
    task_name: m_mmlu_zh
    eval_kwargs:
      num_fewshot: 5
  - evaluation_platform: lm_harness
    task_name: m_mmlu_en
    eval_kwargs:
      num_fewshot: 5
  - evaluation_platform: lm_harness
    task_name: m_mmlu_fr
    eval_kwargs:
      num_fewshot: 5
  - evaluation_platform: lm_harness
    task_name: m_mmlu_de
    eval_kwargs:
      num_fewshot: 5
  - evaluation_platform: lm_harness
    task_name: m_mmlu_hi
    eval_kwargs:
      num_fewshot: 5
  - evaluation_platform: lm_harness
    task_name: m_mmlu_id
    eval_kwargs:
      num_fewshot: 5
  - evaluation_platform: lm_harness
    task_name: m_mmlu_it
    eval_kwargs:
      num_fewshot: 5
  - evaluation_platform: lm_harness
    task_name: m_mmlu_pt
    eval_kwargs:
      num_fewshot: 5
  - evaluation_platform: lm_harness
    task_name: m_mmlu_ro
    eval_kwargs:
      num_fewshot: 5
  - evaluation_platform: lm_harness
    task_name: m_mmlu_ru
    eval_kwargs:
      num_fewshot: 5
  - evaluation_platform: lm_harness
    task_name: m_mmlu_es
    eval_kwargs:
      num_fewshot: 5
  - evaluation_platform: lm_harness
    task_name: m_mmlu_uk
    eval_kwargs:
      num_fewshot: 5
  - evaluation_platform: lm_harness
    task_name: m_mmlu_vi
    eval_kwargs:
      num_fewshot: 5

generation:
  batch_size: 8

enable_wandb: True
