name: llama3-8b-aya-sft

resources:
  accelerators: {"A100": 1}
  any_of:
    - use_spot: true
    - use_spot: false
  disk_size: 200  # Disk size in GB

# Upload working directory to remote ~/sky_workdir.
workdir: .

# Mount local files.
file_mounts:
  ~/.netrc: ~/.netrc # WandB credentials

envs:
  WANDB_PROJECT: oumi-eval
  OUMI_RUN_NAME: llama3.8b.aya.sft

setup: |
  set -e
  pip install uv && uv pip install '.[gpu]'

run: |
  set -e  # Exit if any command failed.
  source ./configs/examples/misc/sky_init.sh

  python -m oumi.evaluate \
    -c configs/projects/aya/evaluation/eval.yaml \
    "run_name='${OUMI_RUN_NAME}.${SKYPILOT_TASK_ID}'"
