# Eval config for Llama 3.2 11B Vision Instruct.
model:
  model_name: "meta-llama/Llama-3.2-11B-Vision-Instruct"
  model_max_length: 256
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  load_pretrained_weights: True
  trust_remote_code: True

generation:
  batch_size: 1

tasks:
  - evaluation_platform: lm_harness
    task_name: mmmu_val

enable_wandb: True
