# Class: oumi.core.configs.JobConfig
# https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/job_config.py

# Config to evaluate smollm 135M on 1 GCP node.
# Example command:
# oumi launch up -c configs/recipes/smollm/evaluation/135m/gcp_job.yaml --cluster smollm-135m-eval
name: smollm-135m-eval

resources:
  cloud: gcp
  accelerators: "A100:1"
  use_spot: true
  disk_size: 100 # Disk size in GBs

working_dir: .

envs:
  OUMI_RUN_NAME: smollm135m.eval
  # https://github.com/huggingface/tokenizers/issues/899#issuecomment-1027739758
  TOKENIZERS_PARALLELISM: false

setup: |
  set -e
  pip install uv && uv pip install '.[gpu,evaluation]'

run: |
  set -e  # Exit if any command failed.
  source ./configs/examples/misc/sky_init.sh

  set -x
  oumi evaluate -c configs/recipes/smollm/evaluation/135m/eval.yaml \
    --enable_wandb false

  echo "Evaluation complete!"
