# Eval config for SmolLM 135M Instruct.

model:
  model_name: "HuggingFaceTB/SmolLM2-135M-Instruct"
  model_max_length: 2048
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  load_pretrained_weights: True
  trust_remote_code: True

generation:
  batch_size: 4

tasks:
  - evaluation_platform: alpaca_eval
    eval_kwargs:
      version: 2.0
