name: llama3-8b-aya-sft

num_nodes: 1  # Set it to N for multi-node training.

resources:
  accelerators: {"A100-80GB-SXM": 8}
  any_of:
    - use_spot: true
    - use_spot: false
  disk_size: 500  # Disk size in GB

# Upload working directory to remote ~/sky_workdir.
workdir: .

# Mount local files.
file_mounts:
  ~/.netrc: ~/.netrc # WandB credentials

envs:
  WANDB_PROJECT: oumi-train
  OUMI_RUN_NAME: llama3.8b.aya.fft
  TOKENIZERS_PARALLELISM: true

setup: |
  set -e
  pip install uv && uv pip install '.[gpu]'

run: |
  set -e  # Exit if any command failed.
  source ./configs/examples/misc/sky_init.sh

  set -x  # Print "torchrun" command with expanded variables
  torchrun \
      --nnodes=${OUMI_NUM_NODES} \
      --node-rank=${SKYPILOT_NODE_RANK} \
      --nproc-per-node=${SKYPILOT_NUM_GPUS_PER_NODE} \
      --master-addr=${OUMI_MASTER_ADDR} \
      --master-port=8007 \
      -m oumi.train \
      -c configs/projects/aya/sft/train.yaml \
      "training.run_name='${OUMI_RUN_NAME}.${SKYPILOT_TASK_ID}'" \
      "training.output_dir=train/" \
      "training.enable_wandb=false" \
      "training.enable_tensorboard=true" \
      "training.include_performance_metrics=true" \
      "training.dataloader_num_workers=1" \
      "training.dataloader_prefetch_factor=1024" \
      "training.logging_steps=10"

  echo "Node ${SKYPILOT_NODE_RANK} is all done!"
