name: llama2b-ddp

resources:
  accelerators: {"A100": 4}
  any_of:
    - use_spot: true
    - use_spot: false

# Upload working directory to remote ~/sky_workdir.
workdir: .

# Mount local files.
file_mounts:
  ~/.netrc: ~/.netrc  # WandB credentials

envs:
  WANDB_PROJECT: oumi-train
  OUMI_RUN_NAME: llama2b.pt
  ACCELERATE_LOG_LEVEL: info

setup: |
  set -e
  pip install uv && uv pip install '.[gpu]'

run: |
  set -e  # Exit if any command failed.
  source ./configs/skypilot/sky_init.sh

  ACCELERATE_MULTI_GPU_OPTION=
  if test ${OUMI_TOTAL_NUM_GPUS} -gt 1; then
    ACCELERATE_MULTI_GPU_OPTION="--multi_gpu"
  fi

  # NOTE: Can't enable gradient checkpointing for compiled DDP models (OPE-209)
  # NOTE: training.compile=true leads to NaN gradients and 0.0 loss (OPE-267)

  set -x  # Print "accelerate launch" command with expanded variables
  accelerate launch \
      --num_machines ${OUMI_NUM_NODES} \
      --machine_rank ${SKYPILOT_NODE_RANK} \
      --num_processes ${OUMI_TOTAL_NUM_GPUS} \
      --main_process_ip ${OUMI_MASTER_ADDR} \
      --main_process_port 8007 \
      ${ACCELERATE_MULTI_GPU_OPTION} \
      --config_file configs/accelerate/llama.ddp.yaml \
      -m oumi.train \
      -c configs/oumi/llama2b.pt.yaml \
      "training.run_name='${OUMI_RUN_NAME}.${SKYPILOT_TASK_ID}'" \
      "training.per_device_train_batch_size=4" \
      "training.gradient_accumulation_steps=64" \
      "training.compile=false" \
      "training.max_steps=20" \
      "training.save_steps=100" \
      "training.save_final_model=true"

  echo "Node ${SKYPILOT_NODE_RANK} is all done!"
