name: gpt2-fsdp

resources:
  accelerators: {"A40": 2}
  any_of:
    - use_spot: true
    - use_spot: false

# Upload working directory to remote ~/sky_workdir.
workdir: .

# Mount local files.
file_mounts:
  ~/.netrc: ~/.netrc  # WandB credentials

envs:
  WANDB_PROJECT: oumi-train
  OUMI_RUN_NAME: gpt2.pt.fsdp
  ACCELERATE_LOG_LEVEL: info

setup: |
  set -e
  pip install uv && uv pip install '.[gpu]'

run: |
  set -e  # Exit if any command failed.
  source ./configs/skypilot/sky_init.sh

  if test ${OUMI_TOTAL_NUM_GPUS} -lt 2; then
    echo "Using FSDP with only 1 GPU may lead to errors. Multiple GPUs are expected."
  fi

  set -x  # Print "accelerate launch" command with expanded variables
  accelerate launch \
      --num_machines ${OUMI_NUM_NODES} \
      --machine_rank ${SKYPILOT_NODE_RANK} \
      --num_processes ${OUMI_TOTAL_NUM_GPUS} \
      --main_process_ip ${OUMI_MASTER_ADDR} \
      --main_process_port 8007 \
      --use_fsdp \
      --config_file configs/accelerate/gpt2.fsdp.yaml \
      -m oumi.train \
      -c configs/oumi/gpt2.pt.yaml \
      "training.run_name='${OUMI_RUN_NAME}.${SKYPILOT_TASK_ID}'" \
      "training.output_dir=train/" \
      "training.enable_wandb=true" \
      "training.enable_tensorboard=true" \
      "training.include_performance_metrics=true" \
      "training.per_device_train_batch_size=8" \
      "training.max_steps=100" \
      "training.logging_steps=10"

  echo "Node ${SKYPILOT_NODE_RANK} is all done!"
