name: llama70b-lora

num_nodes: 2
resources:
  accelerators: {"A100": 4}
  any_of:
    - use_spot: true
    - use_spot: false
  disk_size: 2000  # Disk size in GB

# Upload working directory to remote ~/sky_workdir.
workdir: .

# Mount local files.
file_mounts:
  ~/.netrc: ~/.netrc  # WandB credentials
  # Mount HF token, which is needed to download locked-down models from HF Hub.
  # This is created on the local machine by running `huggingface-cli login`.
  ~/.cache/huggingface/token: ~/.cache/huggingface/token

envs:
  WANDB_PROJECT: oumi-train
  OUMI_RUN_NAME: llama70b.lora
  ACCELERATE_LOG_LEVEL: info
  # https://github.com/huggingface/tokenizers/issues/899#issuecomment-1027739758
  TOKENIZERS_PARALLELISM: false

setup: |
  set -e
  pip install uv && uv pip install '.[gpu]'
  # Download model from GCS, which is faster than downloading during training.
  # At the moment, you need to run this manually after ssh-ing into the cluster
  # because it requires manual authentication.
  # gsutil -m cp -R gs://oumi-dev-us-central1/wizeng/models/models--meta-llama--Meta-Llama-3.1-70B-Instruct ~/.cache/huggingface/hub

run: |
  set -e  # Exit if any command failed.
  source ./configs/skypilot/sky_init.sh

  if test ${OUMI_TOTAL_NUM_GPUS} -lt 2; then
    echo "Using FSDP with only 1 GPU may lead to errors. Multiple GPUs are expected."
  fi

  set -x  # Print "accelerate launch" command with expanded variables
  accelerate launch \
      --num_machines ${OUMI_NUM_NODES} \
      --machine_rank ${SKYPILOT_NODE_RANK} \
      --num_processes ${OUMI_TOTAL_NUM_GPUS} \
      --main_process_ip ${OUMI_MASTER_ADDR} \
      --main_process_port 8007 \
      --use_fsdp \
      --config_file configs/accelerate/llama70b.lora.yaml \
      -m oumi.train \
      -c configs/oumi/llama70b.lora.yaml \
      "training.run_name='${OUMI_RUN_NAME}.${SKYPILOT_TASK_ID}'" \
      "training.max_steps=10" \
      "training.save_steps=10" \
      "training.save_final_model=true"

  echo "Node ${SKYPILOT_NODE_RANK} is all done!"
