# Class: oumi.core.configs.InferenceConfig
# https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/inference_config.py

model:
  model_name: "mistralai/Mistral-Small-Instruct-2409"
  model_max_length: 128
  torch_dtype_str: "bfloat16"
  trust_remote_code: True

generation:
  batch_size: 1

engine: NATIVE
