# Inference config for Llama 8B Instruct.

model:
  # Vocab size: 128256
  # Hidden size: 4096
  # MLP intermediate size: 14336
  # Num layers: 32
  # Num attention heads: 32
  # Num KV heads: 8
  # Weight tying: False
  # Model max length: 131072 (initially trained with 8192)
  model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct"
  adapter_model: null  # Update for LoRA-tuned models.
  model_max_length: 512
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  load_pretrained_weights: True
  trust_remote_code: True

generation:
  max_new_tokens: 512
