# Config to FSDP LoRA tune Llama 3.1 405B Instruct.
# Example command:
# oumi launch up -c configs/recipes/llama3_1/sft/405b_lora/gcp_job.yaml --cluster llama405b-lora-fsdp
name: llama405b-lora-fsdp

num_nodes: 2
resources:
  cloud: gcp
  accelerators: "A100-80GB:8"
  use_spot: true
  disk_size: 4000 # Disk size in GBs
  region: us-central1

working_dir: .

file_mounts:
  ~/.netrc: ~/.netrc  # WandB credentials
  # Mount HF token, which is needed to download locked-down models from HF Hub.
  # This is created on the local machine by running `huggingface-cli login`.
  ~/.cache/huggingface/token: ~/.cache/huggingface/token

storage_mounts:
  /gcs_dir:
    source: gs://oumi-dev-us-central1
    store: gcs

envs:
  WANDB_PROJECT: oumi-train
  OUMI_RUN_NAME: llama405b.lora.fsdp
  ACCELERATE_LOG_LEVEL: info
  # https://github.com/huggingface/tokenizers/issues/899#issuecomment-1027739758
  TOKENIZERS_PARALLELISM: false

setup: |
  set -e
  pip install uv && uv pip install '.[gpu]' hf_transfer
  # Install model from HF Hub. This tool increases download speed compared to
  # downloading the model during training.
  HF_HUB_ENABLE_HF_TRANSFER=1 huggingface-cli download meta-llama/Meta-Llama-3.1-405B-Instruct --exclude original/*

run: |
  set -e  # Exit if any command failed.
  source ./configs/examples/misc/sky_init.sh

  set -x
  oumi distributed torchrun \
      -m oumi train \
      -c configs/recipes/llama3_1/sft/405b_lora/train.yaml \
      --training.run_name "${OUMI_RUN_NAME}.${SKYPILOT_TASK_ID}"

  echo "Node ${SKYPILOT_NODE_RANK} is all done!"
