# Eval config for SmolLM 135M Instruct.

model:
  model_name: "HuggingFaceTB/SmolLM2-135M-Instruct"
  adapter_model: null # Update for LoRA-tuned models.
  model_max_length: 2048
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  load_pretrained_weights: True
  trust_remote_code: True

generation:
  batch_size: 4

tasks:
  - evaluation_platform: lm_harness
    task_name: m_mmlu_en
    eval_kwargs:
      num_fewshot: 5

enable_wandb: True
