###################################################################
# Skypilot Launch Parameters : LoRA SFT Training  of Llama3.1 70B #
###################################################################
#
# Launches 8 A-100:40GB each, on GCP, via FSDP.
#
# Example command:
# sky launch -r --cloud GCP -c llama3.1_70B_lora_sft_fsdp \
# configs/examples/llama3_1/sft/70b_lora/sky_job.yaml
#
####################################################################

envs:
  WANDB_PROJECT: oumi-train
  OUMI_RUN_NAME: llama3.1_70B_lora_sft_fsdp
  ACCELERATE_LOG_LEVEL: info
  TOKENIZERS_PARALLELISM: false

name: llama3.1_70B_lora_sft_fsdp

resources:
  accelerators: {"A100": 8}
  use_spot: true
  disk_size: 500

# Upload working directory to remote ~/sky_workdir.
workdir: .

# Mount local files.
file_mounts:
  ~/.netrc: ~/.netrc  # WandB credentials

  # Mount HF token, which is needed to download locked-down models from HF Hub.
  # This is created on your local machine by running `huggingface-cli login`.
  ~/.cache/huggingface/token: ~/.cache/huggingface/token

setup: |
  set -e
  pip install -e '.[gpu]'

run: |
  set -e  # Exit if any command failed.
  source ./configs/examples/misc/sky_init.sh

  set -x
  torchrun \
      --nnodes=${OUMI_NUM_NODES} \
      --node-rank=${SKYPILOT_NODE_RANK} \
      --nproc-per-node=${SKYPILOT_NUM_GPUS_PER_NODE} \
      --master-addr=${OUMI_MASTER_ADDR} \
      --master-port=8007 \
      -m oumi.train \
      -c configs/examples/llama3_1/sft/70b_lora/train.yaml \
      "training.run_name='${OUMI_RUN_NAME}.${SKYPILOT_TASK_ID}'" \
      "training.output_dir='${OUMI_RUN_NAME}'" \
      "training.logging_dir='${OUMI_RUN_NAME}/runs'"

  echo "Node ${SKYPILOT_NODE_RANK} is all done!"
