name: llama2b-fsdp

resources:
  cloud: gcp
  # See other available accelerators by running `sky show-gpus --cloud gcp`.
  accelerators: "A100:4"
  # To configure single-node, multi-gpu (N GPUs) training, set `accelerators:` above to
  # something like this: "A40:N"

# Upload a working directory to remote ~/sky_workdir.
working_dir: .

# Upload local files.
file_mounts:
  ~/.netrc: ~/.netrc  # mount local netrc file to access private repos
  # /artifacts:
  #   name: lema-dev-private # Not available on lambda
  #   mode: MOUNT

envs:
  WANDB_PROJECT: lema-train-test
  LEMA_RUN_NAME: llama2b.pt.fsdp
  ACCELERATE_LOG_LEVEL: info

setup: |
  set -e
  pip install '.[train]'
  # FLASH_ATTENTION_SKIP_CUDA_BUILD=TRUE pip install flash-attn --no-build-isolation
  pip install flash-attn --no-build-isolation

run: |
  set -e  # Exit if any command failed.

  # Run some checks, and export "LEMA_*" env vars
  source ./configs/skypilot/sky_init.sh

  set -x  # Print "accelerate launch" command with expanded variables
  accelerate launch \
      --num_machines ${LEMA_NUM_NODES} \
      --machine_rank ${SKYPILOT_NODE_RANK} \
      --num_processes $((${LEMA_NUM_NODES} * ${SKYPILOT_NUM_GPUS_PER_NODE})) \
      --main_process_ip ${LEMA_MASTER_ADDR} \
      --main_process_port 8007 \
      --use_fsdp \
      --config_file configs/accelerate/llama.fsdp.yaml \
      -m lema.train \
      -c configs/lema/llama2b.pt.yaml \
      "data.train.experimental_use_async_dataset=true" \
      "training.run_name='${LEMA_RUN_NAME}.${SKYPILOT_TASK_ID}'" \
      "training.max_steps=20" \
      "training.save_steps=0" \
      "training.save_final_model=false" \
      "training.optimizer='adafactor'" \
      "training.per_device_train_batch_size=14" \
      "training.gradient_accumulation_steps=19" \
      "training.dataloader_num_workers=auto" \
      "training.dataloader_prefetch_factor=32" \
      "training.include_performance_metrics=true" \
      "training.ddp_find_unused_parameters=false" \
      "training.try_resume_from_last_checkpoint=false" \
      "training.enable_wandb=true"

  echo "Node ${SKYPILOT_NODE_RANK} is all done!"
