# Pretraining (PT) config for Llama 2B.

model:
  model_name: "HuggingFaceFW/ablation-model-fineweb-v1"
  model_max_length: 2048
  torch_dtype_str: "bfloat16"
  attn_implementation: "flash_attention_2"
  load_pretrained_weights: False
  trust_remote_code: True
  model_kwargs:
    disable_dropout: True

data:
  train:
    datasets:
      - dataset_name: "HuggingFaceFW/fineweb-edu"
        subset: "sample-10BT"
        split: "train"
      # Polaris copy of the dataset:
      # - dataset_name: "/eagle/community_ai/datasets/fineweb-edu/sample-10BT"
      #   subset: "default"
      #   split: "train"
    stream: True
    pack: True
    target_col: "text"

training:
  trainer_type: TRL_SFT
  save_steps: 500
  per_device_train_batch_size: 2 # If gradient checkpointing is enabled: use 12 (~94% of 40GB VRAM)
  gradient_accumulation_steps: 128

  # If enabled, reduces VRAM consumption at the expense of gradients re-computation
  enable_gradient_checkpointing: False
  gradient_checkpointing_kwargs:
    use_reentrant: False
  optimizer: "adamw_torch_fused"
  compile: True

  logging_steps: 10
  log_model_summary: False
  output_dir: "output/llama2b.pt"
  include_performance_metrics: True
