# Eval config for Phi3.
#
# Usage:
#   oumi evaluate -c configs/recipes/phi3/evaluation/eval.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/evaluate/evaluate.html
#   - Config class: oumi.core.configs.EvaluationConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/evaluation_config.py
#   - Other eval configs: configs/**/evaluation/

model:
  model_name: "microsoft/Phi-3-mini-4k-instruct"
  trust_remote_code: True
  shard_for_eval: True

# HuggingFace Leaderboard V1
tasks:
  - evaluation_platform: lm_harness
    task_name: mmlu
    eval_kwargs:
      num_fewshot: 5
  - evaluation_platform: lm_harness
    task_name: arc_challenge
    eval_kwargs:
      num_fewshot: 25
  - evaluation_platform: lm_harness
    task_name: winogrande
    eval_kwargs:
      num_fewshot: 5
  - evaluation_platform: lm_harness
    task_name: hellaswag
    eval_kwargs:
      num_fewshot: 10
  - evaluation_platform: lm_harness
    task_name: truthfulqa_mc2
    eval_kwargs:
      num_fewshot: 0
  - evaluation_platform: lm_harness
    task_name: gsm8k
    eval_kwargs:
      num_fewshot: 5

generation:
  batch_size: 1

enable_wandb: False
